#!/bin/bash

if [ "$1" = "migration" ]; then
  echo "-- $(date "+%b %d, %Y")" >"db/migration/V$(date +%s)__$2.sql"
  echo "Migration Created!"
else
  echo "Must specify type of generated asset. i.e. crud | module | migration"
fi
